export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas — no generic prep."
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations."
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top — making your learning more organized and effective."
  },
  {
    id: "04",
    title: "Understand the 'Why' Behind Answers",
    description:
      "Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic."
  },
  {
    id: "05",
    title: "Mock Interviews with AI",
    description:
      "Simulate real interview environments with AI acting as your interviewer — complete with instant feedback and scoring."
  },
  {
    id: "06",
    title: "Company-Specific Practice",
    description:
      "Practice questions from top companies like Google, Amazon, Microsoft, and more — updated regularly."
  },
  {
    id: "07",
    title: "Track Your Progress",
    description:
      "Visualize your strengths and areas to improve with personalized dashboards and analytics."
  },
  {
    id: "08",
    title: "Resume & Profile Analyzer",
    description:
      "Upload your resume and receive feedback on how to improve it for better chances at your dream role."
  }
];
