// src/utils/data.js

export const CARD_BG = [
  { id: 1, bgcolor: 'linear-gradient(135deg, #1e293b 0%, #0f172a 100%)' }, // Dark Blue-Gray
  { id: 2, bgcolor: 'linear-gradient(135deg, #3f3f46 0%, #27272a 100%)' }, // Cool Gray
  { id: 3, bgcolor: 'linear-gradient(135deg, #0f766e 0%, #115e59 100%)' }, // Teal
  { id: 4, bgcolor: 'linear-gradient(135deg, #4c0519 0%, #7f1d1d 100%)' }, // Deep Red
  { id: 5, bgcolor: 'linear-gradient(135deg, #1e40af 0%, #1e3a8a 100%)' }, // Indigo
  { id: 6, bgcolor: 'linear-gradient(135deg, #3b0764 0%, #6b21a8 100%)' }, // Purple
  { id: 7, bgcolor: 'linear-gradient(135deg, #422006 0%, #78350f 100%)' }, // Warm Brown
  { id: 8, bgcolor: 'linear-gradient(135deg, #064e3b 0%, #065f46 100%)' }, // Forest Green
  { id: 9, bgcolor: 'linear-gradient(135deg, #1f2937 0%, #111827 100%)' }, // Charcoal
  { id: 10, bgcolor: 'linear-gradient(135deg, #3c2a21 0%, #1c1917 100%)' }, // Dark Coffee
];



export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas — no generic prep."
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations."
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top — making your learning more organized and effective."
  },
  {
    id: "04",
    title: "Understand the 'Why' Behind Answers",
    description:
      "Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic."
  },
  {
    id: "05",
    title: "Mock Interviews with AI",
    description:
      "Simulate real interview environments with AI acting as your interviewer — complete with instant feedback and scoring."
  },
  {
    id: "06",
    title: "Company-Specific Practice",
    description:
      "Practice questions from top companies like Google, Amazon, Microsoft, and more — updated regularly."
  },
  {
    id: "07",
    title: "Track Your Progress",
    description:
      "Visualize your strengths and areas to improve with personalized dashboards and analytics."
  },
  {
    id: "08",
    title: "Resume & Profile Analyzer",
    description:
      "Upload your resume and receive feedback on how to improve it for better chances at your dream role."
  }
];
